//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Tool96.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_Tool96TYPE                  130
#define IDD_MYFORM                      310
#define IDD_UNITTOOL                    311
#define IDD_MAP_DLG                     312
#define IDD_OBJECTTAB                   314
#define IDD_PATHFIND                    315
#define IDD_OBJ_DLG                     316
#define IDD_TILEINFO                    317
#define IDD_UNITTAB                     318
#define IDD_SPRITE_DLG                  319
#define IDD_SOUNDTAB                    320
#define IDD_TEXTUREKEYDLG               321
#define IDC_BUTTON1                     1000
#define IDC_PLAY_BTN                    1000
#define IDC_DELETE_BTN                  1000
#define IDC_EDIT1                       1001
#define IDC_BUTTON4                     1001
#define IDC_PAUSE_BTN                   1001
#define IDC_HP_EDIT                     1001
#define IDC_EDIT2                       1002
#define IDC_OBJ_KEY_EDIT                1002
#define IDC_KEY_OBJ_EDIT                1002
#define IDC_EDIT3                       1003
#define IDC_STATE_KEY_EDIT              1003
#define IDC_SAVE_BTN                    1003
#define IDC_KEY_STATE_EDIT              1003
#define IDC_EDIT4                       1004
#define IDC_R_EDIT                      1004
#define IDC_KEY_B_OBJ_EDIT              1004
#define IDC_EDIT5                       1005
#define IDC_G_EDIT                      1005
#define IDC_KEY_B_STATE_EDIT            1005
#define IDC_BUTTON2                     1006
#define IDC_LIST1                       1007
#define IDC_RADIO1                      1008
#define IDC_BUTTON5                     1008
#define IDC_OBJ_RADIO                   1008
#define IDC_RADIO2                      1009
#define IDC_TILE_RADIO                  1009
#define IDC_RADIO3                      1010
#define IDC_BUTTON6                     1010
#define IDC_CHECK1                      1011
#define IDC_PATH_FIND_LOAD_BTN          1011
#define IDC_B_EDIT                      1011
#define IDC_CHECK2                      1012
#define IDC_FX_EDIT                     1012
#define IDC_CHECK3                      1013
#define IDC_FY_EDIT                     1013
#define IDC_INT_EDIT                    1013
#define IDC_BUTTON3                     1014
#define IDC_STAB_EDIT                   1014
#define IDC_TAB1                        1015
#define IDC_MP_EDIT                     1015
#define IDC_PICTURE                     1016
#define IDC_COMBOBOXEX1                 1016
#define IDC_MR_EDIT                     1016
#define IDC_COMBOBOXEX2                 1017
#define IDC_SLIDER1                     1017
#define IDC_ADD_PATH_BTN                1017
#define IDC_HACK_EDIT                   1017
#define IDC_EDIT6                       1018
#define IDC_SLIDER2                     1018
#define IDC_RESET_BTN                   1018
#define IDC_AGI_EDIT                    1018
#define IDC_EDIT7                       1019
#define IDC_DEL_BTN                     1019
#define IDC_SLIDER3                     1019
#define IDC_DEX_EDIT                    1019
#define IDC_EDIT8                       1020
#define IDC_COPY_BTN                    1020
#define IDC_DEF_EDIT                    1020
#define IDC_EDIT9                       1021
#define IDC_HJ_MAP_SAVE_BTN             1022
#define IDC_EDIT_BTN                    1022
#define IDC_MAP_SAVE_BTN                1022
#define IDC_HJ_TILE_LIST                1023
#define IDC_TILE_LIST                   1023
#define IDC_MAP_CATEGORY_LIST           1024
#define IDC_HJ_TILE_PIC                 1026
#define IDC_TILE_PIC                    1026
#define IDC_HJ_STAGE_LIST2              1027
#define IDC_STAGE_LIST2                 1027
#define IDC_MAP_LIST                    1027
#define IDC_OBJ_PIC                     1028
#define IDC_HJ_SCALE_SLIDER             1030
#define IDC_MAP_SCALE_SLIDER            1030
#define IDC_HJ_STAGE_SIZE_TEXT          1031
#define IDC_STAGE_SIZE_TEXT             1031
#define IDC_HJ_SCALE_TEXT               1032
#define IDC_MAP_SCALE_TEXT              1032
#define IDC_HJ_SCALE_TEXT2              1033
#define IDC_HJ_APPLY_BTN                1034
#define IDC_TILE_RESET_BTN              1034
#define IDC_HJ_MAP_LOAD_BTN             1035
#define IDC_OBJ_RESET_BTN               1035
#define IDC_HJ_SPRITE_TREE              1036
#define IDC_ALPHA_TEXT                  1036
#define IDC_TEST_STATIC                 1037
#define IDC_PATH_STATIC                 1037
#define IDC_ALPHA_SLIDER                1037
#define IDC_HJ_SPRITE_NUM_LIST          1038
#define IDC_HJ_SPRITE_PIC               1039
#define IDC_OBJ_SCALE_TEXT              1039
#define IDC_PATH_FIND_SAVE_BTN          1040
#define IDC_OBJ_SCALE_SLIDER            1040
#define IDC_PATH_FIND_LIST              1041
#define IDC_REVERSE_CHECK               1042
#define IDC_PATH_LIST                   1045
#define IDC_COLOR_KEY_PIC               1046
#define IDC_COLOR_CHECKBOX              1048
#define IDC_SPRITE_SPEED_SLIDER         1049
#define IDC_SPRITE_SPEED_TEXT           1050
#define IDC_POS_CHECKBOX                1051
#define IDC_LOAD_BTN                    1052
#define IDC_COMBO1                      1053
#define IDC_UNIT_UNITCOMBO              1054
#define IDC_OBJ_LIST                    1058
#define IDC_OBJ_COMBO                   1059
#define IDC_TI_CATEGORY                 1060
#define IDC_TI_MAP                      1061
#define IDC_MAP_PIC                     1062
#define IDC_UNIT_UNITLIST               1063
#define IDC_UNIT_MAPCOMBO               1065
#define IDC_UNIT_MAPLIST                1066
#define IDC_UNIT_PIC                    1067
#define IDC_KEY_CHECK                   1068
#define IDC_KEY_PATH_COMBO              1069
#define IDC_UNIT_MAP_SLIDER             1070
#define IDC_UNIT_SCALE_TEXT             1071
#define IDC_CUR_UNIT_LIST               1072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           322
#endif
#endif
